pipeline {
    agent any

    tools {
        gradle 'Gradle_8' // Убедись, что такое имя указано в Jenkins → Global Tool Configuration
    }

    environment {
        ALLURE_RESULTS = 'build/allure-results'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                echo 'Running tests...'
                sh './gradlew clean test'
            }
        }

        stage('Allure Report') {
            steps {
                allure includeProperties: false,
                       jdk: '',
                       results: [[path: "${env.ALLURE_RESULTS}"]]
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/build/allure-results/**/*', fingerprint: true
        }

        failure {
            echo 'Build failed.'
        }

        success {
            echo 'Build succeeded.'
        }
    }
}